name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    if: github.event_name != 'schedule' || github.repository == 'diego-ninja/laravel-metronome'

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        symfony: ['7.1']
        php: ['8.2', '8.3', '8.4']
        dependency_version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - Symfony ^${{ matrix.symfony }} - ${{ matrix.os }} - ${{ matrix.dependency_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install PHP dependencies
        shell: bash
        run: composer update --${{ matrix.dependency_version }} --no-interaction --no-progress --ansi --with="symfony/console:^${{ matrix.symfony }}"

      - name: Unit Tests
        run: composer test:unit

      - name: Parallel Tests
        run: composer test:parallel

      - name: Integration Tests
        run: composer test:integration